- name: Deploy to Tomcat
  hosts: web
  become: yes

  tasks:
    - name: Copy WAR file to Tomcat
      copy:
        src: "{{ lookup('env','WORKSPACE') }}/target/MavenAnsibleWebApp2.war"
        dest: /opt/tomcat/webapps/MavenAnsibleWebApp2.war
        remote_src: no

    - name: Restart Tomcat
      systemd:
        name: tomcat
        state: restarted
